<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Discord.Net.targets" />
  <Import Project="../../StyleAnalyzer.targets" />
  <PropertyGroup>
    <AssemblyName>Discord.Net.Core</AssemblyName>
    <RootNamespace>Discord</RootNamespace>
    <Description>The core components for the Discord.Net library.</Description>
    <TargetFramework>netstandard2.1</TargetFramework>
    <WarningLevel>5</WarningLevel>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <IsTrimmable>false</IsTrimmable>
    <IsAotCompatible>false</IsAotCompatible>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Linq.AsyncEnumerable" Version="10.0.0" />
    <PackageReference Include="IDisposableAnalyzers" Version="4.0.8">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Collections.Immutable" Version="10.0.1" />
  </ItemGroup>
</Project>
